app/urls.py
from django.urls import path
from .views.lembrete_views import *
from .views.funcionario.usuario_views import *
from .views.doador.doador_views import *
from .views.agendamento.agendamento_views import *
from .views.tiposangue.tiposangue_views import *
from.views.hospital.hospital_views import *
from.views.dispersao.dispersao_views import *
from.views.doacao.doacao_views import *
from.views.home.home_views import *
from.views.tela_descanso_home.tela_descanso_home_views import *

urlpatterns = [
    path('', tela_descanso_home, name='tela_descanso_home'),
    path('home',home, name='home'),
    path('listar_agendamentos',listar_agendamentos,name='listar_agendamentos'),
    path('listar_doador',listar_doador,name='listar_doador'),
    path('listar_hospital',listar_hospital,name='listar_hospital'),
    path('listar_tiposangue',listar_tiposangue,name='listar_tiposangue'),
    path('editar_tiposangue/<int:id>',editar_tiposangue,name='editar_tiposangue'),
    path('excluir_tiposangue/<int:id>',excluir_tiposangue,name='excluir_tiposangue'),
    path('cadastrar_doador',cadastrar_doador,name='cadastrar_doador'),
    path('cadastrar_tiposangue',cadastrar_tiposangue,name='cadastrar_tiposangue'),
    path('cadastrar_hospital',cadastrar_hospital,name='cadastrar_hospital'),
    path('editar_hospital/<int:id>',editar_hospital,name='editar_hospital'),
    path('excluir_hospital/<int:id>',excluir_hospital,name='excluir_hospital'),
    path('solicitar_dispersao',solicitar_dispersao,name='solicitar_dispersao'),
    path('listar_dispersao',listar_dispersao,name='listar_dispersao'),
    path('editar_dispersao/<int:id>',editar_dispersao,name='editar_dispersao'),
    path('excluir_dispersao/<int:id>',excluir_dispersao,name='excluir_dispersao'),
    path('inserir_doacao',inserir_doacao,name='inserir_doacao'),
    path('listar_doacao',listar_doacao,name='listar_doacao'),
    path('editar_doacao/<int:id>',editar_doacao,name='editar_doacao'),
    path('excluir_doacao/<int:id>',excluir_doacao,name='excluir_doacao'),
    path('cadastrar_agendamento',cadastrar_agendamento,name='cadastrar_agendamento'),
    path('editar_agendamento/<int:id>', editar_agendamento, name='editar_agendamento'),
    path('excluir_agendamento/<int:id>', excluir_agendamento, name='excluir_agendamento'),
    path('editar_doador/<int:id>', editar_doador, name='editar_doador'),
    path('excluir_doador/<int:id>', excluir_doador, name='excluir_doador'),
    path('cadastrar_usuario/', cadastrar_usuario, name='cadastrar_usuario'),
    path('logar_usuario/', logar_usuario, name='logar_usuario'),
    path('deslogar_usuario/', deslogar_usuario, name='deslogar_usuario')
]

gerenciador_lembretes/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('app.urls')),  # importar arquivo urls.py do app
]

app/models.py
from django.core.validators import MinValueValidator
from django.contrib.auth.models import User
from django.db import models
import datetime

# Create your models here.
class TipoSangue(models.Model):
    tipo = models.CharField(max_length=45,null=False,blank=False)
    quantidade = models.IntegerField()

    def __str__(self):
        return self.tipo

class Hospital(models.Model):
    cnpj = models.CharField(max_length=45,null=False,blank=False)
    nome = models.CharField(max_length=200,null=False,blank=False)
    endereco = models.CharField(max_length=200,null=False,blank=False)
    telefone = models.CharField(max_length=15,null=False,blank= False)
    email = models.EmailField(max_length=45,null=False,blank=False)

    def __str__(self):
        return self.nome

class Funcionario(models.Model):
    nome = models.CharField(max_length=45,null=False,blank= False)
    cpf = models.BigIntegerField(null=False,blank=False)
    endereco = models.CharField(max_length=210,null=False,blank=False)
    telefone = models.CharField(max_length=15,null=False,blank=False)
    usuario = models.ForeignKey(User, null=False, on_delete=models.CASCADE,blank=False,default=1)

    PRIORIDADE_CHOICES = [
        ('S','Sim'),
        ('N','Não')
    ]

        
    prioridade = models.CharField(max_length=1,choices= PRIORIDADE_CHOICES, null=False,blank=False,default='N')

    def __str__(self):
        return str(self.nome)

class Dispersao(models.Model):
    cod_func= models.ForeignKey(Funcionario, on_delete=models.CASCADE,null=False,blank=False)
    cod_hospital = models.ForeignKey(Hospital, on_delete=models.CASCADE,null=False,blank=False)
    cod_tiposang = models.ForeignKey(TipoSangue, on_delete=models.CASCADE,null=False,blank=False)
    qtd_bolsa = models.IntegerField(null=False,blank=False)
    data = models.DateField(null=False,blank=False)

class Doador(models.Model):
    cod_tiposang = models.ForeignKey(TipoSangue, on_delete=models.CASCADE,null=False,blank=False)
    nome = models.CharField(max_length=100,null=False,blank=False)
    endereco = models.CharField(max_length=200,null=False,blank=False)
    cpf = models.BigIntegerField(null=False,blank=False)
    telefone = models.CharField(max_length=15,null=False,blank=False)
    data_nascimento = models.DateField(null=False,blank=False)
    peso = models.CharField(max_length=20,null=False,blank=False)

    def __str__(self):
        return self.nome

class Agendamento(models.Model):
    cod_doador = models.ForeignKey(Doador, on_delete=models.CASCADE, null=False,blank=False,default=1)
    data_hora = models.DateTimeField(null=False,blank=False)

    def __str__(self):
        return self.data_hora.strftime("%Y-%m-%d %H:%M:%S")

class Doacao(models.Model):
    cod_agen = models.ForeignKey(Agendamento, on_delete=models.CASCADE,null=False,blank=False)
    cod_func = models.ForeignKey(Funcionario, on_delete=models.CASCADE,null=False,blank=False)
    data_hora = models.DateTimeField(null=False,blank=False)

app/views/lembrete_views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.template import loader
from ..forms import *
from ..entidades.funcionario import Funcionario
from ..services import lembrete_service


# com login_required exibe o método apenas se o usuário estiver logado, se não, redireciona para página de login
@login_required()
def listar_lembretes(request):
    lembretes = lembrete_service.listar_lembretes(request.user)
    return render(request, 'lembretes/listar_lembretes.html', {'lembretes': lembretes})


@login_required()
def cadastrar_lembrete(request):
    if request.method == 'POST':
        # se o método for == POST, vai passar os dados da requisição para o formulário
        form_lembrete = LembreteForm(request.POST)
        if form_lembrete.is_valid():
            # captura as infos que vieram do formulário
            titulo = form_lembrete.cleaned_data['titulo']
            descricao = form_lembrete.cleaned_data['descricao']
            data = form_lembrete.cleaned_data['data']
            prioridade = form_lembrete.cleaned_data['prioridade']
            novo_lembrete = Lembrete(titulo=titulo, descricao=descricao, data=data,
                                    prioridade=prioridade, usuario=request.user)
            # envia o objeto com os dados para o lembrete_service, que insere no BD
            lembrete_service.cadastrar_lembrete(novo_lembrete)
            return redirect('listar_lembretes')
    else:
        # cria uma instância vazia do formulário caso o método não seja POST
        form_lembrete = LembreteForm()
    return render(request, 'lembretes/form_lembrete.html', {'form_lembrete': form_lembrete})


@login_required()
def editar_lembrete(request, id):
    # armazena o lembrete que o usuário está buscando através do id
    lembrete_bd = lembrete_service.listar_lembrete_id(id)
    # aviso caso o usuário tente editar um lembrete que ele nao tem acesso, através da url
    if lembrete_bd.usuario != request.user:
        return HttpResponse('Não permitido')
    form_lembrete = LembreteForm(request.POST or None, instance=lembrete_bd)
    if form_lembrete.is_valid():
        titulo = form_lembrete.cleaned_data['titulo']
        descricao = form_lembrete.cleaned_data['descricao']
        data = form_lembrete.cleaned_data['data']
        prioridade = form_lembrete.cleaned_data['prioridade']
        novo_lembrete = Lembrete(titulo=titulo, descricao=descricao, data=data,
                                prioridade=prioridade, usuario=request.user)
        lembrete_service.editar_lembrete(lembrete_bd, novo_lembrete)
        return redirect('listar_lembretes')

    return render(request, 'lembretes/form_lembrete.html', {'form_lembrete': form_lembrete})


@login_required()
def excluir_lembrete(request, id):
    lembrete_bd = lembrete_service.listar_lembrete_id(id)
    if lembrete_bd.usuario != request.user:
        return HttpResponse('Não permitido')
    if request.method == 'POST':
        lembrete_service.excluir_lembrete(lembrete_bd)
        return redirect('listar_lembretes')
    return render(request, 'lembretes/confirmar_exclusao.html', {'lembrete': lembrete_bd})

app/templates/lembretes/confirmar_exclusao.html
{% extends 'base.html' %}

{% block titulo %}
Confirmar exclusão
{% endblock titulo %}

{% block conteudo %}

<div class="py-3">
  <div class="card mb-3">
    <div class="card-header">
      <h3>Tem certeza que deseja excluir o lembrete abaixo?</h3>
    </div>
    <div class="card-body">
      <h5 class="card-title"> {{ lembrete.titulo }} </h5>
      <p class="card-text"> {{ lembrete.descricao }} </p>
      <hr>
      <form method="POST">
        {% csrf_token %}
        <button class="btn btn-danger" type="submit">Excluir</button>
        <!-- o META.HTTP.REFERER pega a ultima rota que o usuário estava -->
        <a href="{{ request.META.HTTP_REFERER }}"><button type="button" class="btn btn-primary custom-btn">Voltar</button></a>
      </form>
    </div>
  </div>
</div>

{% endblock conteudo %}

app/templates/lembretes/form_lembrete.html
{% extends 'base.html' %}  <!--herança de template-->
{% load meus_filtros %}

{% block titulo %}
Cadastrar lembrete
{% endblock titulo %}

{% block conteudo %}

    <form method="POST" class="formulario">
        {% csrf_token %}
        <div class="form-group">
            <label>Título: </label>
            {{ form_lembrete.titulo|addclass:'form-control' }}
            {{ form_lembrete.titulo.errors }}
        </div>
        <div class="form-group">
            <label>Descrição: </label>
            {{ form_lembrete.descricao|addclass:'form-control' }}
            {{ form_lembrete.descricao.errors }}
        </div>
        <div class="form-group">
            <label>Data: </label>
            {{ form_lembrete.data|addclass:'form-control' }}
            {{ form_lembrete.data.errors }}
        </div>
        <div class="form-group">
            <label>Prioridade: </label>
            {{ form_lembrete.prioridade|addclass:'form-control' }}
            {{ form_lembrete.prioridade.errors }}
        </div>
        <div class="form-group">
            <input type="submit" class="btn btn-primary mb-3" value="Salvar">
            <a href="{{ request.META.HTTP_REFERER }}" class="btn btn-primary mb-3"> Voltar</a>
        </div>
    </form>

{% endblock conteudo %}

app/templates/lembretes/listar_lembretes.html
{% extends 'base.html' %}  <!--herança de template-->

{% block titulo %}
Lista de lembretes
{% endblock titulo %}

{% block conteudo %}

<h1 class="py-3">Lista de Lembretes</h1>

    {% for i in lembretes %}

        <div class="card mb-3">
            <div class="card-header">
                Prioridade: {{ i.get_prioridade_display }}
            </div>
            <div class="card-body">
                <h4 class="card-title"> {{ i.titulo }} </h4>
                <h6 class="card-subtitle"> {{ i.data }} </h6>
                <p class="card-text"> {{ i.descricao }} </p>
                <hr>
                <a href="{% url 'editar_lembrete' i.id %}"><button type="button" class="btn btn-primary custom-btn">Editar</button></a>
                <a href="{% url 'excluir_lembrete' i.id %}"><button type="button" class="btn btn-primary custom-btn">Excluir</button></a>
            </div>
        </div>

    {% endfor %}

<a href="{% url 'cadastrar_lembrete' %}"><input type="button" class="btn btn-primary mb-3" value="Cadastrar novo lembrete"></a>

{% endblock conteudo %}